[package]
name = "seemless"
version = "0.1.0"
authors = ["Harjasleen Malvai <hmalvai@fb.com>"]
edition = "2018"

[dependencies]
crypto = { git  = "https://github.com/novifinancial/winterfell", package = "winter-crypto", branch = "main" }
math = { git  = "https://github.com/novifinancial/winterfell", package = "winter-math", branch = "main" }

rand = "0.8"
queues = "1.0.0"
keyed_priority_queue = "0.3"

[dev-dependencies]
lazy_static = "1.4.0"
