[package]
name = "akd_integration_tests"
version = "0.0.0"
authors = ["Harjasleen Malvai <hmalvai@fb.com>", "Kevin Lewi <klewi@fb.com>", "Sean Lawlor <seanlawlor@fb.com>"]
edition = "2018"
publish = false

[dependencies]
winter-crypto = "0.2"
winter-math = "0.2"

[dev-dependencies]
log = { version = "0.4.8", features = ["kv_unstable"] }
tokio = { version = "1.10", features = ["full"] }
akd = { path = "../akd", features = ["rand"] }
akd_mysql = { path = "../akd_mysql" }
serial_test = "*"
mysql_async = "0.29"
rand = "0.8"
once_cell = "1"
thread-id = "3"
multi_log = "0.1"
clap = "2"
hex = "0.4.3"
