[package]
name = "akd_integration_tests"
version = "0.0.0"
authors = ["Harjasleen Malvai <hmalvai@fb.com>", "Kevin Lewi <klewi@fb.com>", "Sean Lawlor <seanlawlor@fb.com>"]
edition = "2018"
publish = false

[dependencies]
winter-crypto = "0.2"
winter-math = "0.2"

[dev-dependencies]
log = { version = "0.4.8", features = ["kv_unstable"] }
serial_test = "*"
mysql_async = "0.29"
once_cell = "1"
thread-id = "3"
multi_log = "0.1"
hex = "0.4.3"

tokio = { version = "1.10", features = ["full"] }
# regex = "1.5"
rand = "0.7"
# serde_yaml = "0.8"
# serde = "1.0"
# async-trait = "0.1"

akd = { path = "../akd", features = ["public-tests", "rand", "serde_serialization"] }
akd_mysql = { path = "../akd_mysql" }
